---
- name: Install rsync (dependency)
  become: true
  apt:
    name: rsync

- name: Create mariadb directory
  file:
    path: /opt/cloud-1/db
    state: directory
    mode: '0755'

- name: Sync database worktree
  synchronize:
    src: ../files/
    dest: /opt/wordpress/db/
    recursive: true
    delete: true